In [1]:
import numpy as np

In [2]:
# Q1. Create an array of ten zeros?

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Q2. Create an array of ten ones?

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# Q3. Create an array of ten 5s?

In [7]:
np.ones(10)*(5)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
np.zeros(10)+(5)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
# Q4. Create an array of integers from 10 to 50?

In [10]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
# Q5. Create an array of all the even integers from 10 to 50?

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
# Q6. Create 3*3 matrix with values ranging from 0 to 8?

In [16]:
a=np.arange(0,9)

In [17]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# Q7. Create 3*3 identity matrix?

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Q8. Use numpy to generate random number between 0 and 1?

In [22]:
np.random.randn(1)

array([0.13868568])

In [23]:
# Q9. Use numpy to generate an array of 25 random numbers 
# sampled from a standard normal distribution?

In [25]:
b=np.random.randn(25)

In [26]:
b

array([ 0.6591041 ,  0.98745507, -0.55109941, -0.19589582, -0.061703  ,
        0.09883263, -0.65641434,  0.74958706,  0.70040785, -0.66628886,
        0.07465281, -0.60685574, -1.0362836 , -0.36160523, -2.17971544,
        0.95869553,  0.84158119,  1.05532354, -0.61630535,  1.44524648,
       -0.18325536, -1.01477191, -0.09534229, -0.96069969,  0.42489656])

In [28]:
# Q10. Create matrix

In [29]:
# 1--->

In [2]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [3]:
#M2-->
lst=np.arange(0.01,1.01,0.01)
np.array(lst).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [41]:
# Q11. Create an array of 20 linearly spaced points between 0 and 1?

In [42]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [43]:
# Q12. Numpy indexing and selection
# Now you will be given few matrices, and be asked to replicate the resulting matrix outputs

In [45]:
arr=np.arange(1,26).reshape(5,5)

In [46]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [47]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [48]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [49]:
arr[2:20,1:15]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [52]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
arr[0:3,1]

array([ 2,  7, 12])

In [61]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [62]:
arr[4:]

array([[21, 22, 23, 24, 25]])

In [63]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
arr[3,4:]

array([20])

In [68]:
arr[3,4]

20

In [69]:
# Q13. Get the sum of matrix?

In [70]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
arr.sum()

325

In [73]:
# Q14. Get the standard deviation of the values in matrix?

In [74]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
arr.std()

7.211102550927978

In [76]:
# Q15. Get the sum of all the columns in matrix?

In [77]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [79]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [80]:
arr.sum(axis=1)[0]

15